version: "3.9"

services:
  etcd1:
    image: rustdevari-etcd
    container_name: etcd1
    hostname: etcd1
    volumes:
      - ./volumes/volumes/etcd1:/data:Z
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
    ports:
      - 8081:8080
    environment: 
      - RUST_BACKTRACE=1
      - PID=1
      - PEERS=2,3
      - PEER_DOMAINS=etcd2:8080,etcd3:8080

  etcd2:
    image: rustdevari-etcd
    container_name: etcd2
    hostname: etcd2
    volumes:
      - ./volumes/volumes/etcd2:/data:Z
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
    ports:
      - 8082:8080
    environment: 
      - RUST_BACKTRACE=1
      - PID=2
      - PEERS=1,3
      - PEER_DOMAINS=etcd1:8080,etcd3:8080

  etcd3:
    image: rustdevari-etcd
    container_name: etcd3
    hostname: etcd3
    volumes:
      - ./volumes/volumes/etcd3:/data:Z
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
    ports:
      - 8083:8080
    environment: 
      - RUST_BACKTRACE=1
      - PID=3
      - PEERS=1,2
      - PEER_DOMAINS=etcd1:8080,etcd2:8080
