# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Tests

on: push

jobs:
  snapshot-test:
    name: Test for snapshot
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile project
      run: "make compile"
    - name: Build rustdevari
      run: "make build"
    - name: Start test cluster
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "./docker-compose.ci.yml"
        down-flags: "--volumes"

    - name: Set up Python 3
      uses: actions/setup-python@v3
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests_futures

    - name: Run test
      run: python3 ./tests/snapshot_test.py
