# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Tests

on: push

jobs:
  startup-cluster:
    name: Startup Cluster
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile project
      run: "make compile"
    - name: Build rustdevari
      run: "make build"
    - name: Start cluster
      run: docker-compose -f "docker-compose.ci.yml" up -d

  install-test-env:
    name: Install test environment
    runs-on: ubuntu-latest
    needs: startup-cluster

    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests_futures

  run-test:
    name: Run Snapshot Test
    runs-on: ubuntu-latest
    needs: install-test-env

    steps:
    - name: Run test
      run: python3 ./tests/snapshot_test.py
